language: python
python:
  - "2.7"

env:
  matrix:
    - TRAVIS_DB=sqlite
    - TRAVIS_DB=postgresql

addons:
  postgresql: "9.3"

install:
  # Jan 2015: travis-ci runs Ubuntu 12.04 64bit which doesn't have chromedriver
  - wget -P /tmp http://chromedriver.storage.googleapis.com/2.12/chromedriver_linux64.zip
  - sudo unzip /tmp/chromedriver_linux64.zip -d /usr/bin
  - sudo chmod +rx /usr/bin/chromedriver

  - curl -L https://github.com/mozilla/geckodriver/releases/download/v0.19.0/geckodriver-v0.19.0-linux64.tar.gz -o /tmp/geckodriver.tar
  - sudo tar -xzvf /tmp/geckodriver.tar -C /usr/bin/
  - sudo chmod +rx /usr/bin/geckodriver

  - openssl aes-256-cbc -K $encrypted_d69011779259_key -iv $encrypted_d69011779259_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - cd schedulesite/schedulesite
  - cp settings_travis.py.template settings.py
  - cd -
  - pip install -r req.txt
  - psql -c 'create database futuschedule;' -U postgres
  - npm install
  - PATH=./node_modules/.bin:$PATH
  - bower install
  - jsx --no-cache-dir schedulesite/futuschedule/static/futuschedule/js/src schedulesite/futuschedule/static/futuschedule/js/build
  # 'collectstatic' isn't needed for running the tests at the time of writing,
  # this only checks that the command itself works (it's used in deployment).
  - mkdir static
  - schedulesite/manage.py collectstatic --clear --noinput

script: xvfb-run schedulesite/manage.py test futuschedule --settings=schedulesite.settings_test
